### ISSUE TITLE
Android向けcolors.xmlがそのままAndroid Studioで使えない

### ISSUE THREAD

**Issue by CH3COOH** [griffin-stewie/clg#18]
生成したcolors.xmlは以下のようになっています。

```
<!-- Palette generated by clg -->
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="thumbnail_background">#00FFFFFF</color>
</resources>
```

このファイルをAndroid Studioで使おうとすると、下記のビルドエラーが発生します。このエラーはxmlタグから始まらないと表示されてしまうようです。

```
Error: "[xX][mM][lL]"と一致する処理命令ターゲットは許可されていません。
```

IDE上では下図のようにエラーが表示されています。

<img width="464" alt="2017-04-03 10 04 44" src="https://cloud.githubusercontent.com/assets/137952/24592692/b43d2434-1855-11e7-94ff-ebfb4d3d5f31.png">

解決方法としては、`<!-- Palette generated by clg -->`を入れない、もしくはresourcesタグの直下に移動させる必要がありそうです。

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Palette generated by clg -->
    <color name="thumbnail_background">#00FFFFFF</color>
</resources>
```

**Comment by griffin-stewie** [comment]
@CH3COOH 
そうだったんですね。自分は Android の開発経験がないので知りませんでした。
自動生成されている旨は個人的に合った方が良いとおもうのでresourcesタグの直下に移動させる案を採用したいと思います。

**Comment by CH3COOH** [comment]
@griffin-stewie 

では以下のように出力されるように修正しますね、またPRします。

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Palette generated by clg -->
    <color name="hoge_background">#00FFFFFF</color>
    <color name="piyo_background">#00FFFFFF</color>
</resources>
```

**Comment by griffin-stewie** [comment]
ありがとうございます
